export const patientHealthStatus = {
  primary_motivations_weight: "",
  have_target_weight: "",
  target_weight: "",
  how_struggled_weight: "",
  approaches_methods: "",
  your_main_challenges: "",
  suffer_following: "",
  pregnant_lactic: "",
  diagnosed_conditions: "",
  taking_medications: "",
  taking_Ozempic: "",
  twentyFive_starting_dose: "",
  list_current_medications: "",
  allergic_to_these: "",
  allergies_none: "",
  current_weight_height: "",
  ethnic_groups: "",
  BMI_range: "",
};
